package sendorder

import (
	"errors"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/quickfixgo/enum"
	"github.com/quickfixgo/field"
	nos50sp2 "github.com/quickfixgo/fix50sp2/newordersingle"
	"github.com/quickfixgo/quickfix"
	"github.com/quickfixgo/tag"
	"github.com/rs/zerolog"
	"github.com/shopspring/decimal"
	"github.com/spf13/cobra"

	"sylr.dev/fix/config"
	"sylr.dev/fix/pkg/application"
	"sylr.dev/fix/pkg/dict"
	"sylr.dev/fix/pkg/initiator"
	"sylr.dev/fix/pkg/utils"
)

var (
	optionSide, optionType string
	optionSymbol, optionID string
	optionExpiry           string
	optionQuantity         int64
	optionPrice            float64
)

var SendOrderCmd = &cobra.Command{
	Use:               "order",
	Short:             "Send a FIX order",
	Long:              "Send a FIX order after initiating a session with a FIX acceptor.",
	Args:              cobra.ExactArgs(0),
	ValidArgsFunction: cobra.NoFileCompletions,
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		err := Validate(cmd, args)
		if err != nil {
			return err
		}

		if cmd.HasParent() {
			parent := cmd.Parent()
			if parent.PersistentPreRunE != nil {
				return parent.PersistentPreRunE(cmd, args)
			}
		}
		return nil
	},
	RunE: Execute,
}

func init() {
	SendOrderCmd.Flags().StringVar(&optionSide, "side", "", "Order side (buy, sell ... etc)")
	SendOrderCmd.Flags().StringVar(&optionType, "type", "", "Order type (market, limit, stop ... etc)")
	SendOrderCmd.Flags().StringVar(&optionSymbol, "symbol", "", "Order symbol")
	SendOrderCmd.Flags().Int64Var(&optionQuantity, "quantity", 1, "Order quantity")
	SendOrderCmd.Flags().StringVar(&optionID, "id", "", "Order id (uuid autogenerated if not given)")
	SendOrderCmd.Flags().StringVar(&optionExpiry, "expiry", "day", "Order expiry (day, good_till_cancel ... etc)")
	SendOrderCmd.Flags().Float64Var(&optionPrice, "price", 0.0, "Order price")

	SendOrderCmd.MarkFlagRequired("side")
	SendOrderCmd.MarkFlagRequired("type")
	SendOrderCmd.MarkFlagRequired("symbol")
	SendOrderCmd.MarkFlagRequired("quantity")

	SendOrderCmd.RegisterFlagCompletionFunc("side", completeOrderSide)
	SendOrderCmd.RegisterFlagCompletionFunc("type", completeOrderType)
	SendOrderCmd.RegisterFlagCompletionFunc("expiry", completeOrderTimeInForce)
	SendOrderCmd.RegisterFlagCompletionFunc("symbol", cobra.NoFileCompletions)
}

func Validate(cmd *cobra.Command, args []string) error {
	sides := prettyTags(dict.OrderSidesReversed)
	search := utils.Search(sides, strings.ToLower(optionSide))
	if search < 0 {
		return fmt.Errorf("unknown order side")
	}

	types := prettyTags(dict.OrderTypesReversed)
	search = utils.Search(types, strings.ToLower(optionType))
	if search < 0 {
		return fmt.Errorf("unknown order type")
	}

	if len(optionID) == 0 {
		uid := uuid.New()
		optionID = uid.String()
	}

	return nil
}

func Execute(cmd *cobra.Command, args []string) error {
	options := config.GetOptions()
	consoleWriter := zerolog.ConsoleWriter{
		Out:        os.Stdout,
		TimeFormat: time.RFC822,
	}
	multi := zerolog.MultiLevelWriter(consoleWriter)
	logger := zerolog.New(multi).With().Timestamp().Logger().Level(config.IntToZerologLevel(options.Verbose))

	if options.LogCaller {
		logger = logger.With().Caller().Logger()
	}

	context, err := config.GetCurrentContext()
	if err != nil {
		return err
	}

	session, err := context.GetSession()
	if err != nil {
		return err
	}

	acceptor, err := context.GetAcceptor()
	if err != nil {
		return err
	}

	settings, err := context.ToQuickFixSettings()
	if err != nil {
		return err
	}

	app := application.NewSendOrder()
	app.Logger = &logger
	app.Settings = settings
	app.FixVersion = session.DefaultApplVerID

	init, err := initiator.Initiate(app, settings)
	if err != nil {
		return err
	}

	// Start session
	err = init.Start()
	if err != nil {
		return err
	}

	defer init.Stop()

	// Choose right timeout cli option > config > default value (5s)
	var timeout time.Duration
	if options.Timeout != time.Duration(0) {
		timeout = options.Timeout
	} else if acceptor.SocketTimeout != time.Duration(0) {
		timeout = acceptor.SocketTimeout
	} else {
		timeout = 5 * time.Second
	}

	// Wait for session connection
	select {
	case <-time.After(timeout):
		return fmt.Errorf("connection timeout")
	case <-app.Connected:
	}

	eside, err := dict.OrderSideStringToEnum(optionSide)
	if err != nil {
		return err
	}

	etype, err := dict.OrderTypeStringToEnum(optionType)
	if err != nil {
		return err
	}

	eExpiry, err := dict.OrderTimeInForceStringToEnum(optionExpiry)
	if err != nil {
		return err
	}

	// Prepare order
	clordid := field.NewClOrdID(optionID)
	ordside := field.NewSide(eside)
	transactime := field.NewTransactTime(time.Now())
	ordtype := field.NewOrdType(etype)
	quantity := field.NewOrderQty(decimal.NewFromInt(optionQuantity), 2)

	order := nos50sp2.New(clordid, ordside, transactime, ordtype)
	order.SetHandlInst("1")
	order.Set(field.NewSymbol(optionSymbol))
	order.Set(quantity)
	order.Set(field.NewPrice(decimal.NewFromFloat(optionPrice), 2))
	order.Set(field.NewTimeInForce(eExpiry))
	order.Header.Set(field.NewTargetCompID(session.TargetCompID))
	order.Header.Set(field.NewSenderCompID(session.SenderCompID))

	// Send the order
	err = quickfix.Send(order)
	if err != nil {
		return err
	}

	// Wait for the order response
	var responseMessage *quickfix.Message
	select {
	case <-time.After(timeout):
		return fmt.Errorf("timeout while waiting for order response")
	case responseMessage = <-app.FromAppChan:
	}

	// Extract fields from the response
	ordStatus := field.OrdStatusField{}
	text := field.TextField{}
	responseMessage.Body.GetField(tag.OrdStatus, &ordStatus)
	responseMessage.Body.GetField(tag.Text, &text)
	responseMessage.Body.GetField(tag.ClOrdID, &clordid)
	responseMessage.Body.GetField(tag.OrderQty, &quantity)

	switch ordStatus.Value() {
	case enum.OrdStatus_NEW:
		fmt.Printf("Order accepted: ClOrdID=%s OrderQty=%s\n", clordid.String(), quantity.Decimal.String())
		utils.MessageTable(os.Stdout, responseMessage, session.DefaultApplVerID)
	case enum.OrdStatus_REJECTED:
		err = errors.New("Order rejected")
		if len(text.String()) > 0 {
			err = fmt.Errorf("%w: %s", err, text.String())
		}
	default:
		err = errors.New("Order status unknown")
		if len(text.String()) > 0 {
			err = fmt.Errorf("%w: %s", err, text.String())
		}
		return err
	}

	return err
}
